In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('Data/dataset_merged.csv')

In [4]:
df.head()

,platform,video_id,video_url,video_title,video_core_content,video_key_highlights,video_target_sentiment,video_cultural_context,uploader,upload_date,...,comment_count,share_count,duration_seconds,comment_id,comment_text,comment_author,comment_author_id,comment_like_count,comment_reply_count,comment_create_time
0,youtube,5Augh75jX6g,https://www.youtube.com/watch?v=5Augh75jX6g,HIGHLIGHTS: ARSENAL - BOURNEMOUTH,Diễn biến trận đấu kịch tính giữa Arsenal và B...,"Những sai lầm phòng ngự của Arsenal, pha penal...",Hỗn hợp (Mixed): Căng thẳng/Thất vọng,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Thưởng thức những trận cầu Ngoại hạng Anh đỉnh...,NaN,NaN,NaN,NaN,NaN
1,youtube,5Augh75jX6g,https://www.youtube.com/watch?v=5Augh75jX6g,HIGHLIGHTS: ARSENAL - BOURNEMOUTH,Diễn biến trận đấu kịch tính giữa Arsenal và B...,"Những sai lầm phòng ngự của Arsenal, pha penal...",Hỗn hợp (Mixed): Căng thẳng/Thất vọng,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Thu mơ ăn 6\r\nĐông ăn 4\r\nXuân bắt đầu buông...,NaN,NaN,NaN,NaN,NaN
2,youtube,5Augh75jX6g,https://www.youtube.com/watch?v=5Augh75jX6g,HIGHLIGHTS: ARSENAL - BOURNEMOUTH,Diễn biến trận đấu kịch tính giữa Arsenal và B...,"Những sai lầm phòng ngự của Arsenal, pha penal...",Hỗn hợp (Mixed): Căng thẳng/Thất vọng,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"Vcl cái lối đá, sút xa kiếm góc xong phạt góc ...",NaN,NaN,NaN,NaN,NaN
3,youtube,5Augh75jX6g,https://www.youtube.com/watch?v=5Augh75jX6g,HIGHLIGHTS: ARSENAL - BOURNEMOUTH,Diễn biến trận đấu kịch tính giữa Arsenal và B...,"Những sai lầm phòng ngự của Arsenal, pha penal...",Hỗn hợp (Mixed): Căng thẳng/Thất vọng,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Phốn lào ko làm tôi ngạc nhiên với lối đá tầm ...,NaN,NaN,NaN,NaN,NaN
4,youtube,5Augh75jX6g,https://www.youtube.com/watch?v=5Augh75jX6g,HIGHLIGHTS: ARSENAL - BOURNEMOUTH,Diễn biến trận đấu kịch tính giữa Arsenal và B...,"Những sai lầm phòng ngự của Arsenal, pha penal...",Hỗn hợp (Mixed): Căng thẳng/Thất vọng,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"Mỗi năm phấn đào nở,\nLại thấy ông đồ gù.\nBày...",NaN,NaN,NaN,NaN,NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10049 entries, 0 to 10048
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   platform                10049 non-null  object
 1   video_id                10049 non-null  object
 2   video_url               10049 non-null  object
 3   video_title             10049 non-null  object
 4   video_core_content      10049 non-null  object
 5   video_key_highlights    9416 non-null   object
 6   video_target_sentiment  10049 non-null  object
 7   video_cultural_context  3166 non-null   object
 8   uploader                4057 non-null   object
 9   upload_date             4057 non-null   float64
 10  view_count              4057 non-null   float64
 11  like_count              4057 non-null   float64
 12  comment_count           4057 non-null   float64
 13  share_count             4057 non-null   float64
 14  duration_seconds        4057 non-null   float64
 15  comment_id              4057 non-null   float64
 16  comment_text            10049 non-null  object
 17  comment_author          4057 non-null   object
 18  comment_author_id       4057 non-null   float64
 19  comment_like_count      4057 non-null   float64
 20  comment_reply_count     4057 non-null   float64
 21  comment_create_time     4057 non-null   object
dtypes: float64(10), object(12)
memory usage: 1.7+ MB

In [6]:
df.describe()

,upload_date,view_count,like_count,comment_count,share_count,duration_seconds,comment_id,comment_author_id,comment_like_count,comment_reply_count
count,4.057000e+03,4.057000e+03,4057.000000,4057.000000,4057.000000,4057.000000,4.057000e+03,4.057000e+03,4057.000000,4057.000000
mean,2.026040e+07,2.509880e+06,177587.305891,1253.019473,53521.050037,41.997042,7.627934e+18,6.967885e+18,97.453784,0.640375
std,3.069781e+01,1.894817e+06,133753.053806,1003.660996,30701.305612,39.461151,2.541074e+15,9.567223e+17,1253.128816,4.747269
min,2.026032e+07,4.425000e+05,49300.000000,307.000000,5520.000000,10.000000,7.619512e+18,1.560616e+07,0.000000,0.000000
25%,2.026041e+07,1.100000e+06,86400.000000,599.000000,28300.000000,14.000000,7.628278e+18,6.799150e+18,0.000000,0.000000
50%,2.026041e+07,1.900000e+06,121500.000000,823.000000,48900.000000,27.000000,7.628852e+18,7.094589e+18,1.000000,0.000000
75%,2.026042e+07,2.900000e+06,214200.000000,2760.000000,84000.000000,63.000000,7.629206e+18,7.365436e+18,2.000000,0.000000
max,2.026042e+07,6.300000e+06,454600.000000,3158.000000,100900.000000,174.000000,7.629667e+18,7.628943e+18,38467.000000,102.000000